services:
  valkey:
    image: docker.io/bitnami/valkey:8.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - valkey-data:/bitnami/valkey/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    restart: unless-stopped

  shared:
    build:
      dockerfile: docker/dev.dockerfile
      context: .
      target: shared
    volumes:
      - ./shared:/app/shared
      - shared-dist:/app/shared/dist
      - shared-node-modules:/app/shared/node_modules
      - root-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - TRACEROOT_TOKEN=traceroot-2482242f32984b318ab19c3ed6cf73bc
      - TRACEROOT_SERVICE_NAME=autumn-server
      - TRACEROOT_GITHUB_OWNER=github_owner
      - TRACEROOT_GITHUB_REPO_NAME=autumn
      - TRACEROOT_GITHUB_COMMIT_HASH=main
      - TRACEROOT_ENABLE_SPAN_CLOUD_EXPORT=true
      - TRACEROOT_ENABLE_LOG_CLOUD_EXPORT=true
      - TRACEROOT_ENABLE_SPAN_CONSOLE_EXPORT=true
      - TRACEROOT_ENABLE_LOG_CONSOLE_EXPORT=true
      - TRACEROOT_ENVIRONMENT=development
      - TRACEROOT_LOCAL_MODE=false
    restart: unless-stopped

  # Vite frontend
  vite:
    build:
      dockerfile: docker/dev.dockerfile
      context: .
      target: vite
    ports:
      - "3000:3000"
    volumes:
      - ./vite:/app/vite
      - shared-dist:/app/shared/dist
      - vite-node-modules:/app/vite/node_modules
      - root-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - TRACEROOT_TOKEN=traceroot-2482242f32984b318ab19c3ed6cf73bc
      - TRACEROOT_SERVICE_NAME=autumn-server
      - TRACEROOT_GITHUB_OWNER=github_owner
      - TRACEROOT_GITHUB_REPO_NAME=autumn
      - TRACEROOT_GITHUB_COMMIT_HASH=main
      - TRACEROOT_ENABLE_SPAN_CLOUD_EXPORT=true
      - TRACEROOT_ENABLE_LOG_CLOUD_EXPORT=true
      - TRACEROOT_ENABLE_SPAN_CONSOLE_EXPORT=true
      - TRACEROOT_ENABLE_LOG_CONSOLE_EXPORT=true
      - TRACEROOT_ENVIRONMENT=development
      - TRACEROOT_LOCAL_MODE=false
    depends_on:
      - shared
    restart: unless-stopped

  # Main Express server
  server:
    build:
      dockerfile: docker/dev.dockerfile
      context: .
      target: server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/server
      - shared-dist:/app/shared/dist
      - server-node-modules:/app/server/node_modules
      - root-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://valkey:6379
      - TRACEROOT_TOKEN=traceroot-2482242f32984b318ab19c3ed6cf73bc
      - TRACEROOT_SERVICE_NAME=autumn-server
      - TRACEROOT_GITHUB_OWNER=github_owner
      - TRACEROOT_GITHUB_REPO_NAME=autumn
      - TRACEROOT_GITHUB_COMMIT_HASH=main
      - TRACEROOT_ENABLE_SPAN_CLOUD_EXPORT=true
      - TRACEROOT_ENABLE_LOG_CLOUD_EXPORT=true
      - TRACEROOT_ENABLE_SPAN_CONSOLE_EXPORT=true
      - TRACEROOT_ENABLE_LOG_CONSOLE_EXPORT=true
      - TRACEROOT_ENVIRONMENT=development
      - TRACEROOT_LOCAL_MODE=false
      - TRACEROOT_CONFIG_PATH=app/server/traceroot.config.ts
    env_file:
      - ./server/.env
    depends_on:
      - shared
    restart: unless-stopped

  # BullMQ Workers
  workers:
    build:
      dockerfile: docker/dev.dockerfile
      context: .
      target: workers
    volumes:
      # Mount server source for hot reload (workers use server code)
      - ./server:/app/server
      - shared-dist:/app/shared/dist
      - server-node-modules:/app/server/node_modules
      - root-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://valkey:6379
    env_file:
      - ./server/.env
    depends_on:
      - shared
    restart: unless-stopped

  # Run localtunnel
  localtunnel:
    build:
      dockerfile: docker/dev.dockerfile
      context: .
      target: localtunnel
    volumes:
      - ./server:/app/server
    depends_on:
      - server
    restart: unless-stopped

volumes:
  # Shared package dist output
  shared-dist:
  valkey-data:

  # Node modules volumes to avoid host/container conflicts
  shared-node-modules:
  server-node-modules:
  vite-node-modules:
  root-node-modules:
